### ISSUE TITLE
implement message classes

### ISSUE THREAD

**Issue by lakatosdaniel** [WeDontCSharp/Sokoban#33]
https://docs.google.com/document/d/1iX180_KaU-sitx5YW9UQsLT_hFj9Dt0J9q9zX_evdSE/edit

Implementálni kellene a ControlMessage és a StateChangeMessage leszármazottait.

Branch: **grafi_msg**

**Comment by lakatosdaniel** [comment]
![main](https://user-images.githubusercontent.com/36563337/39935858-b6cf46f4-554a-11e8-816f-adb2b38e86b4.jpg)

**Comment by Saki-EU** [comment]
mikroszoft'd
