### ISSUE TITLE
doksi_4 seq

### ISSUE THREAD

**Issue by lakatosdaniel** [WeDontCSharp/Sokoban#41]
Meg kell csinálni a szekvencia diagramokat a leírások alapján. **Elvileg az 5-ös doksiban benne vannak, úgyhogy csak át kell onann másolni őket.**

**Ezt szerkezd közvetlenül:** (Valamiért feketék a számozások, de eddig is azok voltak, ignore...)
[templ_04.docx](https://github.com/WeDontCSharp/Sokoban/files/1998828/templ_04.docx)

**Comment by mate0515** [comment]
[templ_04.docx](https://github.com/WeDontCSharp/Sokoban/files/2013588/templ_04.docx)
